package com.example.demo.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

public class SOrder implements Serializable {
    /**
     * 
    * id
     */
    private Integer id;

    /**
     * 
    * name
     */
    private String name;

    /**
     * 
    * description
     */
    private String description;

    /**
     * 
    * created_GUID
     */
    private String createdGuid;

    /**
     * 
    * updated_GUID
     */
    private String updatedGuid;

    /**
     * 
    * created_Time
     */
    private LocalDateTime createdTime;

    /**
     * 
    * updated_Time
     */
    private LocalDateTime updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public String getCreatedGuid() {
        return createdGuid;
    }

    public void setCreatedGuid(String createdGuid) {
        this.createdGuid = createdGuid == null ? null : createdGuid.trim();
    }

    public String getUpdatedGuid() {
        return updatedGuid;
    }

    public void setUpdatedGuid(String updatedGuid) {
        this.updatedGuid = updatedGuid == null ? null : updatedGuid.trim();
    }

    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", createdGuid=").append(createdGuid);
        sb.append(", updatedGuid=").append(updatedGuid);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}