package com.example.demo.entity.generatePackage;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Created by Mybatis Generator on 2021/05/10
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ContractSignStatus implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 审批状态
     */
    private String xApproveStatus;

    /**
     * 审批状态枚举值
     */
    private Integer xApproveStatusEnum;

    /**
     * 审批人guid
     */
    private String xApproveUserGUID;

    /**
     * 审批人
     */
    private String xApproveUserName;

    /**
     * 合同guid
     */
    private String xContractGUID;

    /**
     * 发送状态
     */
    private String xSendStatus;

    /**
     * 发送状态枚举值
     */
    private Integer xSendStatusEnum;

    /**
     * 用印状态
     */
    private Integer xYyStatus;

    /**
     * 用印人guid
     */
    private String xYyUserGUID;

    /**
     * 用印人
     */
    private String xYyUserName;

    /**
     * 合同签章状态主键
     */
    private String contractSignStatusGUID;

    /**
     */
    private String createdGUID;

    /**
     */
    private String createdName;

    /**
     */
    private Date createdTime;

    /**
     */
    private String modifiedGUID;

    /**
     */
    private String modifiedName;

    /**
     */
    private Date modifiedTime;

    /**
     * 审批日期
     */
    private Date xApproveTime;

    /**
     * 房管网合同编号
     */
    private String xNetContractNumber;

    /**
     * 总体失败原因
     */
    private String xAuditReason;

    /**
     * 上传时间
     */
    private Date xUploadTime;

    /**
     * 是否测试数据
     */
    private Integer is_testdata;

    /**
     * 是否删除
     */
    private Integer is_deleted;

    /**
     * 版本号
     */
    private Long versionNumber;

    /**
     * 附件
     */
    private String xContractFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignstatus
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xApproveStatus=").append(xApproveStatus);
        sb.append(", xApproveStatusEnum=").append(xApproveStatusEnum);
        sb.append(", xApproveUserGUID=").append(xApproveUserGUID);
        sb.append(", xApproveUserName=").append(xApproveUserName);
        sb.append(", xContractGUID=").append(xContractGUID);
        sb.append(", xSendStatus=").append(xSendStatus);
        sb.append(", xSendStatusEnum=").append(xSendStatusEnum);
        sb.append(", xYyStatus=").append(xYyStatus);
        sb.append(", xYyUserGUID=").append(xYyUserGUID);
        sb.append(", xYyUserName=").append(xYyUserName);
        sb.append(", contractSignStatusGUID=").append(contractSignStatusGUID);
        sb.append(", createdGUID=").append(createdGUID);
        sb.append(", createdName=").append(createdName);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", modifiedGUID=").append(modifiedGUID);
        sb.append(", modifiedName=").append(modifiedName);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", xApproveTime=").append(xApproveTime);
        sb.append(", xNetContractNumber=").append(xNetContractNumber);
        sb.append(", xAuditReason=").append(xAuditReason);
        sb.append(", xUploadTime=").append(xUploadTime);
        sb.append(", is_testdata=").append(is_testdata);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append(", versionNumber=").append(versionNumber);
        sb.append(", xContractFile=").append(xContractFile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}