package com.example.demo.entity.generatePackage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContractSignApproveInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignapproveinfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignapproveinfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignapproveinfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    public ContractSignApproveInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * x_s_contractsignapproveinfo null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXAuditTimeIsNull() {
            addCriterion("x_AuditTime is null");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeIsNotNull() {
            addCriterion("x_AuditTime is not null");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeEqualTo(Date value) {
            addCriterion("x_AuditTime =", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeNotEqualTo(Date value) {
            addCriterion("x_AuditTime <>", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeGreaterThan(Date value) {
            addCriterion("x_AuditTime >", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("x_AuditTime >=", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeLessThan(Date value) {
            addCriterion("x_AuditTime <", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("x_AuditTime <=", value, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeIn(List<Date> values) {
            addCriterion("x_AuditTime in", values, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeNotIn(List<Date> values) {
            addCriterion("x_AuditTime not in", values, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeBetween(Date value1, Date value2) {
            addCriterion("x_AuditTime between", value1, value2, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("x_AuditTime not between", value1, value2, "xAuditTime");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIsNull() {
            addCriterion("x_ContractGUID is null");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIsNotNull() {
            addCriterion("x_ContractGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDEqualTo(String value) {
            addCriterion("x_ContractGUID =", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotEqualTo(String value) {
            addCriterion("x_ContractGUID <>", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDGreaterThan(String value) {
            addCriterion("x_ContractGUID >", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_ContractGUID >=", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLessThan(String value) {
            addCriterion("x_ContractGUID <", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_ContractGUID <=", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLike(String value) {
            addCriterion("x_ContractGUID like", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotLike(String value) {
            addCriterion("x_ContractGUID not like", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIn(List<String> values) {
            addCriterion("x_ContractGUID in", values, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotIn(List<String> values) {
            addCriterion("x_ContractGUID not in", values, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDBetween(String value1, String value2) {
            addCriterion("x_ContractGUID between", value1, value2, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotBetween(String value1, String value2) {
            addCriterion("x_ContractGUID not between", value1, value2, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXCrmWordIsNull() {
            addCriterion("x_CrmWord is null");
            return (Criteria) this;
        }

        public Criteria andXCrmWordIsNotNull() {
            addCriterion("x_CrmWord is not null");
            return (Criteria) this;
        }

        public Criteria andXCrmWordEqualTo(String value) {
            addCriterion("x_CrmWord =", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordNotEqualTo(String value) {
            addCriterion("x_CrmWord <>", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordGreaterThan(String value) {
            addCriterion("x_CrmWord >", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordGreaterThanOrEqualTo(String value) {
            addCriterion("x_CrmWord >=", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordLessThan(String value) {
            addCriterion("x_CrmWord <", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordLessThanOrEqualTo(String value) {
            addCriterion("x_CrmWord <=", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordLike(String value) {
            addCriterion("x_CrmWord like", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordNotLike(String value) {
            addCriterion("x_CrmWord not like", value, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordIn(List<String> values) {
            addCriterion("x_CrmWord in", values, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordNotIn(List<String> values) {
            addCriterion("x_CrmWord not in", values, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordBetween(String value1, String value2) {
            addCriterion("x_CrmWord between", value1, value2, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXCrmWordNotBetween(String value1, String value2) {
            addCriterion("x_CrmWord not between", value1, value2, "xCrmWord");
            return (Criteria) this;
        }

        public Criteria andXIsAuditIsNull() {
            addCriterion("x_IsAudit is null");
            return (Criteria) this;
        }

        public Criteria andXIsAuditIsNotNull() {
            addCriterion("x_IsAudit is not null");
            return (Criteria) this;
        }

        public Criteria andXIsAuditEqualTo(Integer value) {
            addCriterion("x_IsAudit =", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditNotEqualTo(Integer value) {
            addCriterion("x_IsAudit <>", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditGreaterThan(Integer value) {
            addCriterion("x_IsAudit >", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_IsAudit >=", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditLessThan(Integer value) {
            addCriterion("x_IsAudit <", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditLessThanOrEqualTo(Integer value) {
            addCriterion("x_IsAudit <=", value, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditIn(List<Integer> values) {
            addCriterion("x_IsAudit in", values, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditNotIn(List<Integer> values) {
            addCriterion("x_IsAudit not in", values, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditBetween(Integer value1, Integer value2) {
            addCriterion("x_IsAudit between", value1, value2, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("x_IsAudit not between", value1, value2, "xIsAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditIsNull() {
            addCriterion("x_IsContractAudit is null");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditIsNotNull() {
            addCriterion("x_IsContractAudit is not null");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditEqualTo(Integer value) {
            addCriterion("x_IsContractAudit =", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditNotEqualTo(Integer value) {
            addCriterion("x_IsContractAudit <>", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditGreaterThan(Integer value) {
            addCriterion("x_IsContractAudit >", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_IsContractAudit >=", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditLessThan(Integer value) {
            addCriterion("x_IsContractAudit <", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditLessThanOrEqualTo(Integer value) {
            addCriterion("x_IsContractAudit <=", value, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditIn(List<Integer> values) {
            addCriterion("x_IsContractAudit in", values, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditNotIn(List<Integer> values) {
            addCriterion("x_IsContractAudit not in", values, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditBetween(Integer value1, Integer value2) {
            addCriterion("x_IsContractAudit between", value1, value2, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXIsContractAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("x_IsContractAudit not between", value1, value2, "xIsContractAudit");
            return (Criteria) this;
        }

        public Criteria andXOrcWordIsNull() {
            addCriterion("x_OrcWord is null");
            return (Criteria) this;
        }

        public Criteria andXOrcWordIsNotNull() {
            addCriterion("x_OrcWord is not null");
            return (Criteria) this;
        }

        public Criteria andXOrcWordEqualTo(String value) {
            addCriterion("x_OrcWord =", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordNotEqualTo(String value) {
            addCriterion("x_OrcWord <>", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordGreaterThan(String value) {
            addCriterion("x_OrcWord >", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordGreaterThanOrEqualTo(String value) {
            addCriterion("x_OrcWord >=", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordLessThan(String value) {
            addCriterion("x_OrcWord <", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordLessThanOrEqualTo(String value) {
            addCriterion("x_OrcWord <=", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordLike(String value) {
            addCriterion("x_OrcWord like", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordNotLike(String value) {
            addCriterion("x_OrcWord not like", value, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordIn(List<String> values) {
            addCriterion("x_OrcWord in", values, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordNotIn(List<String> values) {
            addCriterion("x_OrcWord not in", values, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordBetween(String value1, String value2) {
            addCriterion("x_OrcWord between", value1, value2, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXOrcWordNotBetween(String value1, String value2) {
            addCriterion("x_OrcWord not between", value1, value2, "xOrcWord");
            return (Criteria) this;
        }

        public Criteria andXWordNameIsNull() {
            addCriterion("x_WordName is null");
            return (Criteria) this;
        }

        public Criteria andXWordNameIsNotNull() {
            addCriterion("x_WordName is not null");
            return (Criteria) this;
        }

        public Criteria andXWordNameEqualTo(String value) {
            addCriterion("x_WordName =", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameNotEqualTo(String value) {
            addCriterion("x_WordName <>", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameGreaterThan(String value) {
            addCriterion("x_WordName >", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameGreaterThanOrEqualTo(String value) {
            addCriterion("x_WordName >=", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameLessThan(String value) {
            addCriterion("x_WordName <", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameLessThanOrEqualTo(String value) {
            addCriterion("x_WordName <=", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameLike(String value) {
            addCriterion("x_WordName like", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameNotLike(String value) {
            addCriterion("x_WordName not like", value, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameIn(List<String> values) {
            addCriterion("x_WordName in", values, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameNotIn(List<String> values) {
            addCriterion("x_WordName not in", values, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameBetween(String value1, String value2) {
            addCriterion("x_WordName between", value1, value2, "xWordName");
            return (Criteria) this;
        }

        public Criteria andXWordNameNotBetween(String value1, String value2) {
            addCriterion("x_WordName not between", value1, value2, "xWordName");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDIsNull() {
            addCriterion("ContractSignApproveInfoGUID is null");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDIsNotNull() {
            addCriterion("ContractSignApproveInfoGUID is not null");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDEqualTo(String value) {
            addCriterion("ContractSignApproveInfoGUID =", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDNotEqualTo(String value) {
            addCriterion("ContractSignApproveInfoGUID <>", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDGreaterThan(String value) {
            addCriterion("ContractSignApproveInfoGUID >", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("ContractSignApproveInfoGUID >=", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDLessThan(String value) {
            addCriterion("ContractSignApproveInfoGUID <", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDLessThanOrEqualTo(String value) {
            addCriterion("ContractSignApproveInfoGUID <=", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDLike(String value) {
            addCriterion("ContractSignApproveInfoGUID like", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDNotLike(String value) {
            addCriterion("ContractSignApproveInfoGUID not like", value, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDIn(List<String> values) {
            addCriterion("ContractSignApproveInfoGUID in", values, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDNotIn(List<String> values) {
            addCriterion("ContractSignApproveInfoGUID not in", values, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDBetween(String value1, String value2) {
            addCriterion("ContractSignApproveInfoGUID between", value1, value2, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignApproveInfoGUIDNotBetween(String value1, String value2) {
            addCriterion("ContractSignApproveInfoGUID not between", value1, value2, "contractSignApproveInfoGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNull() {
            addCriterion("CreatedGUID is null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNotNull() {
            addCriterion("CreatedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDEqualTo(String value) {
            addCriterion("CreatedGUID =", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotEqualTo(String value) {
            addCriterion("CreatedGUID <>", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThan(String value) {
            addCriterion("CreatedGUID >", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedGUID >=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThan(String value) {
            addCriterion("CreatedGUID <", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThanOrEqualTo(String value) {
            addCriterion("CreatedGUID <=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLike(String value) {
            addCriterion("CreatedGUID like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotLike(String value) {
            addCriterion("CreatedGUID not like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIn(List<String> values) {
            addCriterion("CreatedGUID in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotIn(List<String> values) {
            addCriterion("CreatedGUID not in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDBetween(String value1, String value2) {
            addCriterion("CreatedGUID between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotBetween(String value1, String value2) {
            addCriterion("CreatedGUID not between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNull() {
            addCriterion("CreatedName is null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNotNull() {
            addCriterion("CreatedName is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameEqualTo(String value) {
            addCriterion("CreatedName =", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotEqualTo(String value) {
            addCriterion("CreatedName <>", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThan(String value) {
            addCriterion("CreatedName >", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedName >=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThan(String value) {
            addCriterion("CreatedName <", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThanOrEqualTo(String value) {
            addCriterion("CreatedName <=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLike(String value) {
            addCriterion("CreatedName like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotLike(String value) {
            addCriterion("CreatedName not like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIn(List<String> values) {
            addCriterion("CreatedName in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotIn(List<String> values) {
            addCriterion("CreatedName not in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameBetween(String value1, String value2) {
            addCriterion("CreatedName between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotBetween(String value1, String value2) {
            addCriterion("CreatedName not between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNull() {
            addCriterion("ModifiedGUID is null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNotNull() {
            addCriterion("ModifiedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDEqualTo(String value) {
            addCriterion("ModifiedGUID =", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotEqualTo(String value) {
            addCriterion("ModifiedGUID <>", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThan(String value) {
            addCriterion("ModifiedGUID >", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID >=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThan(String value) {
            addCriterion("ModifiedGUID <", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID <=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLike(String value) {
            addCriterion("ModifiedGUID like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotLike(String value) {
            addCriterion("ModifiedGUID not like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIn(List<String> values) {
            addCriterion("ModifiedGUID in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotIn(List<String> values) {
            addCriterion("ModifiedGUID not in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDBetween(String value1, String value2) {
            addCriterion("ModifiedGUID between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotBetween(String value1, String value2) {
            addCriterion("ModifiedGUID not between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNull() {
            addCriterion("ModifiedName is null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNotNull() {
            addCriterion("ModifiedName is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameEqualTo(String value) {
            addCriterion("ModifiedName =", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotEqualTo(String value) {
            addCriterion("ModifiedName <>", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThan(String value) {
            addCriterion("ModifiedName >", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedName >=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThan(String value) {
            addCriterion("ModifiedName <", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThanOrEqualTo(String value) {
            addCriterion("ModifiedName <=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLike(String value) {
            addCriterion("ModifiedName like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotLike(String value) {
            addCriterion("ModifiedName not like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIn(List<String> values) {
            addCriterion("ModifiedName in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotIn(List<String> values) {
            addCriterion("ModifiedName not in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameBetween(String value1, String value2) {
            addCriterion("ModifiedName between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotBetween(String value1, String value2) {
            addCriterion("ModifiedName not between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("ModifiedTime is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("ModifiedTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("ModifiedTime =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("ModifiedTime <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("ModifiedTime >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("ModifiedTime <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("ModifiedTime in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("ModifiedTime not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNull() {
            addCriterion("VersionNumber is null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNotNull() {
            addCriterion("VersionNumber is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberEqualTo(Date value) {
            addCriterion("VersionNumber =", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotEqualTo(Date value) {
            addCriterion("VersionNumber <>", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThan(Date value) {
            addCriterion("VersionNumber >", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThanOrEqualTo(Date value) {
            addCriterion("VersionNumber >=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThan(Date value) {
            addCriterion("VersionNumber <", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThanOrEqualTo(Date value) {
            addCriterion("VersionNumber <=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIn(List<Date> values) {
            addCriterion("VersionNumber in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotIn(List<Date> values) {
            addCriterion("VersionNumber not in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberBetween(Date value1, Date value2) {
            addCriterion("VersionNumber between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotBetween(Date value1, Date value2) {
            addCriterion("VersionNumber not between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andXWordReasonIsNull() {
            addCriterion("x_WordReason is null");
            return (Criteria) this;
        }

        public Criteria andXWordReasonIsNotNull() {
            addCriterion("x_WordReason is not null");
            return (Criteria) this;
        }

        public Criteria andXWordReasonEqualTo(String value) {
            addCriterion("x_WordReason =", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonNotEqualTo(String value) {
            addCriterion("x_WordReason <>", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonGreaterThan(String value) {
            addCriterion("x_WordReason >", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonGreaterThanOrEqualTo(String value) {
            addCriterion("x_WordReason >=", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonLessThan(String value) {
            addCriterion("x_WordReason <", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonLessThanOrEqualTo(String value) {
            addCriterion("x_WordReason <=", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonLike(String value) {
            addCriterion("x_WordReason like", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonNotLike(String value) {
            addCriterion("x_WordReason not like", value, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonIn(List<String> values) {
            addCriterion("x_WordReason in", values, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonNotIn(List<String> values) {
            addCriterion("x_WordReason not in", values, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonBetween(String value1, String value2) {
            addCriterion("x_WordReason between", value1, value2, "xWordReason");
            return (Criteria) this;
        }

        public Criteria andXWordReasonNotBetween(String value1, String value2) {
            addCriterion("x_WordReason not between", value1, value2, "xWordReason");
            return (Criteria) this;
        }
    }

    /**
     * x_s_contractsignapproveinfo
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * x_s_contractsignapproveinfo null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}