package com.example.demo.entity.generatePackage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContractSignStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignstatus
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignstatus
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_contractsignstatus
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    public ContractSignStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * x_s_contractsignstatus null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusIsNull() {
            addCriterion("x_ApproveStatus is null");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusIsNotNull() {
            addCriterion("x_ApproveStatus is not null");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEqualTo(String value) {
            addCriterion("x_ApproveStatus =", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusNotEqualTo(String value) {
            addCriterion("x_ApproveStatus <>", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusGreaterThan(String value) {
            addCriterion("x_ApproveStatus >", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusGreaterThanOrEqualTo(String value) {
            addCriterion("x_ApproveStatus >=", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusLessThan(String value) {
            addCriterion("x_ApproveStatus <", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusLessThanOrEqualTo(String value) {
            addCriterion("x_ApproveStatus <=", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusLike(String value) {
            addCriterion("x_ApproveStatus like", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusNotLike(String value) {
            addCriterion("x_ApproveStatus not like", value, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusIn(List<String> values) {
            addCriterion("x_ApproveStatus in", values, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusNotIn(List<String> values) {
            addCriterion("x_ApproveStatus not in", values, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusBetween(String value1, String value2) {
            addCriterion("x_ApproveStatus between", value1, value2, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusNotBetween(String value1, String value2) {
            addCriterion("x_ApproveStatus not between", value1, value2, "xApproveStatus");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumIsNull() {
            addCriterion("x_ApproveStatusEnum is null");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumIsNotNull() {
            addCriterion("x_ApproveStatusEnum is not null");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumEqualTo(Integer value) {
            addCriterion("x_ApproveStatusEnum =", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumNotEqualTo(Integer value) {
            addCriterion("x_ApproveStatusEnum <>", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumGreaterThan(Integer value) {
            addCriterion("x_ApproveStatusEnum >", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_ApproveStatusEnum >=", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumLessThan(Integer value) {
            addCriterion("x_ApproveStatusEnum <", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumLessThanOrEqualTo(Integer value) {
            addCriterion("x_ApproveStatusEnum <=", value, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumIn(List<Integer> values) {
            addCriterion("x_ApproveStatusEnum in", values, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumNotIn(List<Integer> values) {
            addCriterion("x_ApproveStatusEnum not in", values, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumBetween(Integer value1, Integer value2) {
            addCriterion("x_ApproveStatusEnum between", value1, value2, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveStatusEnumNotBetween(Integer value1, Integer value2) {
            addCriterion("x_ApproveStatusEnum not between", value1, value2, "xApproveStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDIsNull() {
            addCriterion("x_ApproveUserGUID is null");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDIsNotNull() {
            addCriterion("x_ApproveUserGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDEqualTo(String value) {
            addCriterion("x_ApproveUserGUID =", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDNotEqualTo(String value) {
            addCriterion("x_ApproveUserGUID <>", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDGreaterThan(String value) {
            addCriterion("x_ApproveUserGUID >", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_ApproveUserGUID >=", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDLessThan(String value) {
            addCriterion("x_ApproveUserGUID <", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_ApproveUserGUID <=", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDLike(String value) {
            addCriterion("x_ApproveUserGUID like", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDNotLike(String value) {
            addCriterion("x_ApproveUserGUID not like", value, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDIn(List<String> values) {
            addCriterion("x_ApproveUserGUID in", values, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDNotIn(List<String> values) {
            addCriterion("x_ApproveUserGUID not in", values, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDBetween(String value1, String value2) {
            addCriterion("x_ApproveUserGUID between", value1, value2, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserGUIDNotBetween(String value1, String value2) {
            addCriterion("x_ApproveUserGUID not between", value1, value2, "xApproveUserGUID");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameIsNull() {
            addCriterion("x_ApproveUserName is null");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameIsNotNull() {
            addCriterion("x_ApproveUserName is not null");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameEqualTo(String value) {
            addCriterion("x_ApproveUserName =", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameNotEqualTo(String value) {
            addCriterion("x_ApproveUserName <>", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameGreaterThan(String value) {
            addCriterion("x_ApproveUserName >", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("x_ApproveUserName >=", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameLessThan(String value) {
            addCriterion("x_ApproveUserName <", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameLessThanOrEqualTo(String value) {
            addCriterion("x_ApproveUserName <=", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameLike(String value) {
            addCriterion("x_ApproveUserName like", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameNotLike(String value) {
            addCriterion("x_ApproveUserName not like", value, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameIn(List<String> values) {
            addCriterion("x_ApproveUserName in", values, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameNotIn(List<String> values) {
            addCriterion("x_ApproveUserName not in", values, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameBetween(String value1, String value2) {
            addCriterion("x_ApproveUserName between", value1, value2, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXApproveUserNameNotBetween(String value1, String value2) {
            addCriterion("x_ApproveUserName not between", value1, value2, "xApproveUserName");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIsNull() {
            addCriterion("x_ContractGUID is null");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIsNotNull() {
            addCriterion("x_ContractGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDEqualTo(String value) {
            addCriterion("x_ContractGUID =", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotEqualTo(String value) {
            addCriterion("x_ContractGUID <>", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDGreaterThan(String value) {
            addCriterion("x_ContractGUID >", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_ContractGUID >=", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLessThan(String value) {
            addCriterion("x_ContractGUID <", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_ContractGUID <=", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDLike(String value) {
            addCriterion("x_ContractGUID like", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotLike(String value) {
            addCriterion("x_ContractGUID not like", value, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDIn(List<String> values) {
            addCriterion("x_ContractGUID in", values, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotIn(List<String> values) {
            addCriterion("x_ContractGUID not in", values, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDBetween(String value1, String value2) {
            addCriterion("x_ContractGUID between", value1, value2, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXContractGUIDNotBetween(String value1, String value2) {
            addCriterion("x_ContractGUID not between", value1, value2, "xContractGUID");
            return (Criteria) this;
        }

        public Criteria andXSendStatusIsNull() {
            addCriterion("x_SendStatus is null");
            return (Criteria) this;
        }

        public Criteria andXSendStatusIsNotNull() {
            addCriterion("x_SendStatus is not null");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEqualTo(String value) {
            addCriterion("x_SendStatus =", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusNotEqualTo(String value) {
            addCriterion("x_SendStatus <>", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusGreaterThan(String value) {
            addCriterion("x_SendStatus >", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusGreaterThanOrEqualTo(String value) {
            addCriterion("x_SendStatus >=", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusLessThan(String value) {
            addCriterion("x_SendStatus <", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusLessThanOrEqualTo(String value) {
            addCriterion("x_SendStatus <=", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusLike(String value) {
            addCriterion("x_SendStatus like", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusNotLike(String value) {
            addCriterion("x_SendStatus not like", value, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusIn(List<String> values) {
            addCriterion("x_SendStatus in", values, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusNotIn(List<String> values) {
            addCriterion("x_SendStatus not in", values, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusBetween(String value1, String value2) {
            addCriterion("x_SendStatus between", value1, value2, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusNotBetween(String value1, String value2) {
            addCriterion("x_SendStatus not between", value1, value2, "xSendStatus");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumIsNull() {
            addCriterion("x_SendStatusEnum is null");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumIsNotNull() {
            addCriterion("x_SendStatusEnum is not null");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumEqualTo(Integer value) {
            addCriterion("x_SendStatusEnum =", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumNotEqualTo(Integer value) {
            addCriterion("x_SendStatusEnum <>", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumGreaterThan(Integer value) {
            addCriterion("x_SendStatusEnum >", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_SendStatusEnum >=", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumLessThan(Integer value) {
            addCriterion("x_SendStatusEnum <", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumLessThanOrEqualTo(Integer value) {
            addCriterion("x_SendStatusEnum <=", value, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumIn(List<Integer> values) {
            addCriterion("x_SendStatusEnum in", values, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumNotIn(List<Integer> values) {
            addCriterion("x_SendStatusEnum not in", values, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumBetween(Integer value1, Integer value2) {
            addCriterion("x_SendStatusEnum between", value1, value2, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXSendStatusEnumNotBetween(Integer value1, Integer value2) {
            addCriterion("x_SendStatusEnum not between", value1, value2, "xSendStatusEnum");
            return (Criteria) this;
        }

        public Criteria andXYyStatusIsNull() {
            addCriterion("x_YyStatus is null");
            return (Criteria) this;
        }

        public Criteria andXYyStatusIsNotNull() {
            addCriterion("x_YyStatus is not null");
            return (Criteria) this;
        }

        public Criteria andXYyStatusEqualTo(Integer value) {
            addCriterion("x_YyStatus =", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusNotEqualTo(Integer value) {
            addCriterion("x_YyStatus <>", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusGreaterThan(Integer value) {
            addCriterion("x_YyStatus >", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_YyStatus >=", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusLessThan(Integer value) {
            addCriterion("x_YyStatus <", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("x_YyStatus <=", value, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusIn(List<Integer> values) {
            addCriterion("x_YyStatus in", values, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusNotIn(List<Integer> values) {
            addCriterion("x_YyStatus not in", values, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusBetween(Integer value1, Integer value2) {
            addCriterion("x_YyStatus between", value1, value2, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("x_YyStatus not between", value1, value2, "xYyStatus");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDIsNull() {
            addCriterion("x_YyUserGUID is null");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDIsNotNull() {
            addCriterion("x_YyUserGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDEqualTo(String value) {
            addCriterion("x_YyUserGUID =", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDNotEqualTo(String value) {
            addCriterion("x_YyUserGUID <>", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDGreaterThan(String value) {
            addCriterion("x_YyUserGUID >", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_YyUserGUID >=", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDLessThan(String value) {
            addCriterion("x_YyUserGUID <", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_YyUserGUID <=", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDLike(String value) {
            addCriterion("x_YyUserGUID like", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDNotLike(String value) {
            addCriterion("x_YyUserGUID not like", value, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDIn(List<String> values) {
            addCriterion("x_YyUserGUID in", values, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDNotIn(List<String> values) {
            addCriterion("x_YyUserGUID not in", values, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDBetween(String value1, String value2) {
            addCriterion("x_YyUserGUID between", value1, value2, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserGUIDNotBetween(String value1, String value2) {
            addCriterion("x_YyUserGUID not between", value1, value2, "xYyUserGUID");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameIsNull() {
            addCriterion("x_YyUserName is null");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameIsNotNull() {
            addCriterion("x_YyUserName is not null");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameEqualTo(String value) {
            addCriterion("x_YyUserName =", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameNotEqualTo(String value) {
            addCriterion("x_YyUserName <>", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameGreaterThan(String value) {
            addCriterion("x_YyUserName >", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("x_YyUserName >=", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameLessThan(String value) {
            addCriterion("x_YyUserName <", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameLessThanOrEqualTo(String value) {
            addCriterion("x_YyUserName <=", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameLike(String value) {
            addCriterion("x_YyUserName like", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameNotLike(String value) {
            addCriterion("x_YyUserName not like", value, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameIn(List<String> values) {
            addCriterion("x_YyUserName in", values, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameNotIn(List<String> values) {
            addCriterion("x_YyUserName not in", values, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameBetween(String value1, String value2) {
            addCriterion("x_YyUserName between", value1, value2, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andXYyUserNameNotBetween(String value1, String value2) {
            addCriterion("x_YyUserName not between", value1, value2, "xYyUserName");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDIsNull() {
            addCriterion("ContractSignStatusGUID is null");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDIsNotNull() {
            addCriterion("ContractSignStatusGUID is not null");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDEqualTo(String value) {
            addCriterion("ContractSignStatusGUID =", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDNotEqualTo(String value) {
            addCriterion("ContractSignStatusGUID <>", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDGreaterThan(String value) {
            addCriterion("ContractSignStatusGUID >", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("ContractSignStatusGUID >=", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDLessThan(String value) {
            addCriterion("ContractSignStatusGUID <", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDLessThanOrEqualTo(String value) {
            addCriterion("ContractSignStatusGUID <=", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDLike(String value) {
            addCriterion("ContractSignStatusGUID like", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDNotLike(String value) {
            addCriterion("ContractSignStatusGUID not like", value, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDIn(List<String> values) {
            addCriterion("ContractSignStatusGUID in", values, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDNotIn(List<String> values) {
            addCriterion("ContractSignStatusGUID not in", values, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDBetween(String value1, String value2) {
            addCriterion("ContractSignStatusGUID between", value1, value2, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andContractSignStatusGUIDNotBetween(String value1, String value2) {
            addCriterion("ContractSignStatusGUID not between", value1, value2, "contractSignStatusGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNull() {
            addCriterion("CreatedGUID is null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNotNull() {
            addCriterion("CreatedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDEqualTo(String value) {
            addCriterion("CreatedGUID =", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotEqualTo(String value) {
            addCriterion("CreatedGUID <>", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThan(String value) {
            addCriterion("CreatedGUID >", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedGUID >=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThan(String value) {
            addCriterion("CreatedGUID <", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThanOrEqualTo(String value) {
            addCriterion("CreatedGUID <=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLike(String value) {
            addCriterion("CreatedGUID like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotLike(String value) {
            addCriterion("CreatedGUID not like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIn(List<String> values) {
            addCriterion("CreatedGUID in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotIn(List<String> values) {
            addCriterion("CreatedGUID not in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDBetween(String value1, String value2) {
            addCriterion("CreatedGUID between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotBetween(String value1, String value2) {
            addCriterion("CreatedGUID not between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNull() {
            addCriterion("CreatedName is null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNotNull() {
            addCriterion("CreatedName is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameEqualTo(String value) {
            addCriterion("CreatedName =", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotEqualTo(String value) {
            addCriterion("CreatedName <>", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThan(String value) {
            addCriterion("CreatedName >", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedName >=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThan(String value) {
            addCriterion("CreatedName <", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThanOrEqualTo(String value) {
            addCriterion("CreatedName <=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLike(String value) {
            addCriterion("CreatedName like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotLike(String value) {
            addCriterion("CreatedName not like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIn(List<String> values) {
            addCriterion("CreatedName in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotIn(List<String> values) {
            addCriterion("CreatedName not in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameBetween(String value1, String value2) {
            addCriterion("CreatedName between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotBetween(String value1, String value2) {
            addCriterion("CreatedName not between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNull() {
            addCriterion("ModifiedGUID is null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNotNull() {
            addCriterion("ModifiedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDEqualTo(String value) {
            addCriterion("ModifiedGUID =", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotEqualTo(String value) {
            addCriterion("ModifiedGUID <>", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThan(String value) {
            addCriterion("ModifiedGUID >", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID >=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThan(String value) {
            addCriterion("ModifiedGUID <", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID <=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLike(String value) {
            addCriterion("ModifiedGUID like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotLike(String value) {
            addCriterion("ModifiedGUID not like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIn(List<String> values) {
            addCriterion("ModifiedGUID in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotIn(List<String> values) {
            addCriterion("ModifiedGUID not in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDBetween(String value1, String value2) {
            addCriterion("ModifiedGUID between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotBetween(String value1, String value2) {
            addCriterion("ModifiedGUID not between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNull() {
            addCriterion("ModifiedName is null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNotNull() {
            addCriterion("ModifiedName is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameEqualTo(String value) {
            addCriterion("ModifiedName =", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotEqualTo(String value) {
            addCriterion("ModifiedName <>", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThan(String value) {
            addCriterion("ModifiedName >", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedName >=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThan(String value) {
            addCriterion("ModifiedName <", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThanOrEqualTo(String value) {
            addCriterion("ModifiedName <=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLike(String value) {
            addCriterion("ModifiedName like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotLike(String value) {
            addCriterion("ModifiedName not like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIn(List<String> values) {
            addCriterion("ModifiedName in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotIn(List<String> values) {
            addCriterion("ModifiedName not in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameBetween(String value1, String value2) {
            addCriterion("ModifiedName between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotBetween(String value1, String value2) {
            addCriterion("ModifiedName not between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("ModifiedTime is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("ModifiedTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("ModifiedTime =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("ModifiedTime <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("ModifiedTime >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("ModifiedTime <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("ModifiedTime in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("ModifiedTime not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeIsNull() {
            addCriterion("x_ApproveTime is null");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeIsNotNull() {
            addCriterion("x_ApproveTime is not null");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeEqualTo(Date value) {
            addCriterion("x_ApproveTime =", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeNotEqualTo(Date value) {
            addCriterion("x_ApproveTime <>", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeGreaterThan(Date value) {
            addCriterion("x_ApproveTime >", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("x_ApproveTime >=", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeLessThan(Date value) {
            addCriterion("x_ApproveTime <", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("x_ApproveTime <=", value, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeIn(List<Date> values) {
            addCriterion("x_ApproveTime in", values, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeNotIn(List<Date> values) {
            addCriterion("x_ApproveTime not in", values, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeBetween(Date value1, Date value2) {
            addCriterion("x_ApproveTime between", value1, value2, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("x_ApproveTime not between", value1, value2, "xApproveTime");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberIsNull() {
            addCriterion("x_NetContractNumber is null");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberIsNotNull() {
            addCriterion("x_NetContractNumber is not null");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberEqualTo(String value) {
            addCriterion("x_NetContractNumber =", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberNotEqualTo(String value) {
            addCriterion("x_NetContractNumber <>", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberGreaterThan(String value) {
            addCriterion("x_NetContractNumber >", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberGreaterThanOrEqualTo(String value) {
            addCriterion("x_NetContractNumber >=", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberLessThan(String value) {
            addCriterion("x_NetContractNumber <", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberLessThanOrEqualTo(String value) {
            addCriterion("x_NetContractNumber <=", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberLike(String value) {
            addCriterion("x_NetContractNumber like", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberNotLike(String value) {
            addCriterion("x_NetContractNumber not like", value, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberIn(List<String> values) {
            addCriterion("x_NetContractNumber in", values, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberNotIn(List<String> values) {
            addCriterion("x_NetContractNumber not in", values, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberBetween(String value1, String value2) {
            addCriterion("x_NetContractNumber between", value1, value2, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXNetContractNumberNotBetween(String value1, String value2) {
            addCriterion("x_NetContractNumber not between", value1, value2, "xNetContractNumber");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonIsNull() {
            addCriterion("x_AuditReason is null");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonIsNotNull() {
            addCriterion("x_AuditReason is not null");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonEqualTo(String value) {
            addCriterion("x_AuditReason =", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonNotEqualTo(String value) {
            addCriterion("x_AuditReason <>", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonGreaterThan(String value) {
            addCriterion("x_AuditReason >", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonGreaterThanOrEqualTo(String value) {
            addCriterion("x_AuditReason >=", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonLessThan(String value) {
            addCriterion("x_AuditReason <", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonLessThanOrEqualTo(String value) {
            addCriterion("x_AuditReason <=", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonLike(String value) {
            addCriterion("x_AuditReason like", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonNotLike(String value) {
            addCriterion("x_AuditReason not like", value, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonIn(List<String> values) {
            addCriterion("x_AuditReason in", values, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonNotIn(List<String> values) {
            addCriterion("x_AuditReason not in", values, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonBetween(String value1, String value2) {
            addCriterion("x_AuditReason between", value1, value2, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXAuditReasonNotBetween(String value1, String value2) {
            addCriterion("x_AuditReason not between", value1, value2, "xAuditReason");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeIsNull() {
            addCriterion("x_UploadTime is null");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeIsNotNull() {
            addCriterion("x_UploadTime is not null");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeEqualTo(Date value) {
            addCriterion("x_UploadTime =", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeNotEqualTo(Date value) {
            addCriterion("x_UploadTime <>", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeGreaterThan(Date value) {
            addCriterion("x_UploadTime >", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("x_UploadTime >=", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeLessThan(Date value) {
            addCriterion("x_UploadTime <", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("x_UploadTime <=", value, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeIn(List<Date> values) {
            addCriterion("x_UploadTime in", values, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeNotIn(List<Date> values) {
            addCriterion("x_UploadTime not in", values, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeBetween(Date value1, Date value2) {
            addCriterion("x_UploadTime between", value1, value2, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andXUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("x_UploadTime not between", value1, value2, "xUploadTime");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIsNull() {
            addCriterion("is_testdata is null");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIsNotNull() {
            addCriterion("is_testdata is not null");
            return (Criteria) this;
        }

        public Criteria andIs_testdataEqualTo(Integer value) {
            addCriterion("is_testdata =", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotEqualTo(Integer value) {
            addCriterion("is_testdata <>", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataGreaterThan(Integer value) {
            addCriterion("is_testdata >", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_testdata >=", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataLessThan(Integer value) {
            addCriterion("is_testdata <", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataLessThanOrEqualTo(Integer value) {
            addCriterion("is_testdata <=", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIn(List<Integer> values) {
            addCriterion("is_testdata in", values, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotIn(List<Integer> values) {
            addCriterion("is_testdata not in", values, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataBetween(Integer value1, Integer value2) {
            addCriterion("is_testdata between", value1, value2, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotBetween(Integer value1, Integer value2) {
            addCriterion("is_testdata not between", value1, value2, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIs_deletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNull() {
            addCriterion("versionNumber is null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNotNull() {
            addCriterion("versionNumber is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberEqualTo(Long value) {
            addCriterion("versionNumber =", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotEqualTo(Long value) {
            addCriterion("versionNumber <>", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThan(Long value) {
            addCriterion("versionNumber >", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("versionNumber >=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThan(Long value) {
            addCriterion("versionNumber <", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThanOrEqualTo(Long value) {
            addCriterion("versionNumber <=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIn(List<Long> values) {
            addCriterion("versionNumber in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotIn(List<Long> values) {
            addCriterion("versionNumber not in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberBetween(Long value1, Long value2) {
            addCriterion("versionNumber between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotBetween(Long value1, Long value2) {
            addCriterion("versionNumber not between", value1, value2, "versionNumber");
            return (Criteria) this;
        }
    }

    /**
     * x_s_contractsignstatus
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * x_s_contractsignstatus null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}