package com.example.demo.entity.generatePackage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IsOpenContractSignSetEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_isopencontractsignset
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_isopencontractsignset
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_isopencontractsignset
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    public IsOpenContractSignSetEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * x_s_isopencontractsignset null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDIsNull() {
            addCriterion("x_BUGUID is null");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDIsNotNull() {
            addCriterion("x_BUGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDEqualTo(String value) {
            addCriterion("x_BUGUID =", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDNotEqualTo(String value) {
            addCriterion("x_BUGUID <>", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDGreaterThan(String value) {
            addCriterion("x_BUGUID >", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_BUGUID >=", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDLessThan(String value) {
            addCriterion("x_BUGUID <", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_BUGUID <=", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDLike(String value) {
            addCriterion("x_BUGUID like", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDNotLike(String value) {
            addCriterion("x_BUGUID not like", value, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDIn(List<String> values) {
            addCriterion("x_BUGUID in", values, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDNotIn(List<String> values) {
            addCriterion("x_BUGUID not in", values, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDBetween(String value1, String value2) {
            addCriterion("x_BUGUID between", value1, value2, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXBUGUIDNotBetween(String value1, String value2) {
            addCriterion("x_BUGUID not between", value1, value2, "xBUGUID");
            return (Criteria) this;
        }

        public Criteria andXCloseDateIsNull() {
            addCriterion("x_CloseDate is null");
            return (Criteria) this;
        }

        public Criteria andXCloseDateIsNotNull() {
            addCriterion("x_CloseDate is not null");
            return (Criteria) this;
        }

        public Criteria andXCloseDateEqualTo(Date value) {
            addCriterion("x_CloseDate =", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateNotEqualTo(Date value) {
            addCriterion("x_CloseDate <>", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateGreaterThan(Date value) {
            addCriterion("x_CloseDate >", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("x_CloseDate >=", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateLessThan(Date value) {
            addCriterion("x_CloseDate <", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateLessThanOrEqualTo(Date value) {
            addCriterion("x_CloseDate <=", value, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateIn(List<Date> values) {
            addCriterion("x_CloseDate in", values, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateNotIn(List<Date> values) {
            addCriterion("x_CloseDate not in", values, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateBetween(Date value1, Date value2) {
            addCriterion("x_CloseDate between", value1, value2, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseDateNotBetween(Date value1, Date value2) {
            addCriterion("x_CloseDate not between", value1, value2, "xCloseDate");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonIsNull() {
            addCriterion("x_CloseReason is null");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonIsNotNull() {
            addCriterion("x_CloseReason is not null");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEqualTo(String value) {
            addCriterion("x_CloseReason =", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonNotEqualTo(String value) {
            addCriterion("x_CloseReason <>", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonGreaterThan(String value) {
            addCriterion("x_CloseReason >", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonGreaterThanOrEqualTo(String value) {
            addCriterion("x_CloseReason >=", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonLessThan(String value) {
            addCriterion("x_CloseReason <", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonLessThanOrEqualTo(String value) {
            addCriterion("x_CloseReason <=", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonLike(String value) {
            addCriterion("x_CloseReason like", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonNotLike(String value) {
            addCriterion("x_CloseReason not like", value, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonIn(List<String> values) {
            addCriterion("x_CloseReason in", values, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonNotIn(List<String> values) {
            addCriterion("x_CloseReason not in", values, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonBetween(String value1, String value2) {
            addCriterion("x_CloseReason between", value1, value2, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonNotBetween(String value1, String value2) {
            addCriterion("x_CloseReason not between", value1, value2, "xCloseReason");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumIsNull() {
            addCriterion("x_CloseReasonEnum is null");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumIsNotNull() {
            addCriterion("x_CloseReasonEnum is not null");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumEqualTo(Integer value) {
            addCriterion("x_CloseReasonEnum =", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumNotEqualTo(Integer value) {
            addCriterion("x_CloseReasonEnum <>", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumGreaterThan(Integer value) {
            addCriterion("x_CloseReasonEnum >", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_CloseReasonEnum >=", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumLessThan(Integer value) {
            addCriterion("x_CloseReasonEnum <", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumLessThanOrEqualTo(Integer value) {
            addCriterion("x_CloseReasonEnum <=", value, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumIn(List<Integer> values) {
            addCriterion("x_CloseReasonEnum in", values, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumNotIn(List<Integer> values) {
            addCriterion("x_CloseReasonEnum not in", values, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumBetween(Integer value1, Integer value2) {
            addCriterion("x_CloseReasonEnum between", value1, value2, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXCloseReasonEnumNotBetween(Integer value1, Integer value2) {
            addCriterion("x_CloseReasonEnum not between", value1, value2, "xCloseReasonEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignIsNull() {
            addCriterion("x_IsOpenSign is null");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignIsNotNull() {
            addCriterion("x_IsOpenSign is not null");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEqualTo(String value) {
            addCriterion("x_IsOpenSign =", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignNotEqualTo(String value) {
            addCriterion("x_IsOpenSign <>", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignGreaterThan(String value) {
            addCriterion("x_IsOpenSign >", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignGreaterThanOrEqualTo(String value) {
            addCriterion("x_IsOpenSign >=", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignLessThan(String value) {
            addCriterion("x_IsOpenSign <", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignLessThanOrEqualTo(String value) {
            addCriterion("x_IsOpenSign <=", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignLike(String value) {
            addCriterion("x_IsOpenSign like", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignNotLike(String value) {
            addCriterion("x_IsOpenSign not like", value, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignIn(List<String> values) {
            addCriterion("x_IsOpenSign in", values, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignNotIn(List<String> values) {
            addCriterion("x_IsOpenSign not in", values, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignBetween(String value1, String value2) {
            addCriterion("x_IsOpenSign between", value1, value2, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignNotBetween(String value1, String value2) {
            addCriterion("x_IsOpenSign not between", value1, value2, "xIsOpenSign");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumIsNull() {
            addCriterion("x_IsOpenSignEnum is null");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumIsNotNull() {
            addCriterion("x_IsOpenSignEnum is not null");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumEqualTo(Integer value) {
            addCriterion("x_IsOpenSignEnum =", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumNotEqualTo(Integer value) {
            addCriterion("x_IsOpenSignEnum <>", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumGreaterThan(Integer value) {
            addCriterion("x_IsOpenSignEnum >", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_IsOpenSignEnum >=", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumLessThan(Integer value) {
            addCriterion("x_IsOpenSignEnum <", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumLessThanOrEqualTo(Integer value) {
            addCriterion("x_IsOpenSignEnum <=", value, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumIn(List<Integer> values) {
            addCriterion("x_IsOpenSignEnum in", values, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumNotIn(List<Integer> values) {
            addCriterion("x_IsOpenSignEnum not in", values, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumBetween(Integer value1, Integer value2) {
            addCriterion("x_IsOpenSignEnum between", value1, value2, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXIsOpenSignEnumNotBetween(Integer value1, Integer value2) {
            addCriterion("x_IsOpenSignEnum not between", value1, value2, "xIsOpenSignEnum");
            return (Criteria) this;
        }

        public Criteria andXOpenDateIsNull() {
            addCriterion("x_OpenDate is null");
            return (Criteria) this;
        }

        public Criteria andXOpenDateIsNotNull() {
            addCriterion("x_OpenDate is not null");
            return (Criteria) this;
        }

        public Criteria andXOpenDateEqualTo(Date value) {
            addCriterion("x_OpenDate =", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateNotEqualTo(Date value) {
            addCriterion("x_OpenDate <>", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateGreaterThan(Date value) {
            addCriterion("x_OpenDate >", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateGreaterThanOrEqualTo(Date value) {
            addCriterion("x_OpenDate >=", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateLessThan(Date value) {
            addCriterion("x_OpenDate <", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateLessThanOrEqualTo(Date value) {
            addCriterion("x_OpenDate <=", value, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateIn(List<Date> values) {
            addCriterion("x_OpenDate in", values, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateNotIn(List<Date> values) {
            addCriterion("x_OpenDate not in", values, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateBetween(Date value1, Date value2) {
            addCriterion("x_OpenDate between", value1, value2, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXOpenDateNotBetween(Date value1, Date value2) {
            addCriterion("x_OpenDate not between", value1, value2, "xOpenDate");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDIsNull() {
            addCriterion("x_ProjGUID is null");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDIsNotNull() {
            addCriterion("x_ProjGUID is not null");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDEqualTo(String value) {
            addCriterion("x_ProjGUID =", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDNotEqualTo(String value) {
            addCriterion("x_ProjGUID <>", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDGreaterThan(String value) {
            addCriterion("x_ProjGUID >", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("x_ProjGUID >=", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDLessThan(String value) {
            addCriterion("x_ProjGUID <", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDLessThanOrEqualTo(String value) {
            addCriterion("x_ProjGUID <=", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDLike(String value) {
            addCriterion("x_ProjGUID like", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDNotLike(String value) {
            addCriterion("x_ProjGUID not like", value, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDIn(List<String> values) {
            addCriterion("x_ProjGUID in", values, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDNotIn(List<String> values) {
            addCriterion("x_ProjGUID not in", values, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDBetween(String value1, String value2) {
            addCriterion("x_ProjGUID between", value1, value2, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXProjGUIDNotBetween(String value1, String value2) {
            addCriterion("x_ProjGUID not between", value1, value2, "xProjGUID");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateIsNull() {
            addCriterion("x_RYCloseDate is null");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateIsNotNull() {
            addCriterion("x_RYCloseDate is not null");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateEqualTo(Date value) {
            addCriterion("x_RYCloseDate =", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateNotEqualTo(Date value) {
            addCriterion("x_RYCloseDate <>", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateGreaterThan(Date value) {
            addCriterion("x_RYCloseDate >", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("x_RYCloseDate >=", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateLessThan(Date value) {
            addCriterion("x_RYCloseDate <", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateLessThanOrEqualTo(Date value) {
            addCriterion("x_RYCloseDate <=", value, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateIn(List<Date> values) {
            addCriterion("x_RYCloseDate in", values, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateNotIn(List<Date> values) {
            addCriterion("x_RYCloseDate not in", values, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateBetween(Date value1, Date value2) {
            addCriterion("x_RYCloseDate between", value1, value2, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andXRYCloseDateNotBetween(Date value1, Date value2) {
            addCriterion("x_RYCloseDate not between", value1, value2, "xRYCloseDate");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNull() {
            addCriterion("CreatedGUID is null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIsNotNull() {
            addCriterion("CreatedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDEqualTo(String value) {
            addCriterion("CreatedGUID =", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotEqualTo(String value) {
            addCriterion("CreatedGUID <>", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThan(String value) {
            addCriterion("CreatedGUID >", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedGUID >=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThan(String value) {
            addCriterion("CreatedGUID <", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLessThanOrEqualTo(String value) {
            addCriterion("CreatedGUID <=", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDLike(String value) {
            addCriterion("CreatedGUID like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotLike(String value) {
            addCriterion("CreatedGUID not like", value, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDIn(List<String> values) {
            addCriterion("CreatedGUID in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotIn(List<String> values) {
            addCriterion("CreatedGUID not in", values, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDBetween(String value1, String value2) {
            addCriterion("CreatedGUID between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedGUIDNotBetween(String value1, String value2) {
            addCriterion("CreatedGUID not between", value1, value2, "createdGUID");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNull() {
            addCriterion("CreatedName is null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNotNull() {
            addCriterion("CreatedName is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameEqualTo(String value) {
            addCriterion("CreatedName =", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotEqualTo(String value) {
            addCriterion("CreatedName <>", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThan(String value) {
            addCriterion("CreatedName >", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedName >=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThan(String value) {
            addCriterion("CreatedName <", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThanOrEqualTo(String value) {
            addCriterion("CreatedName <=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLike(String value) {
            addCriterion("CreatedName like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotLike(String value) {
            addCriterion("CreatedName not like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIn(List<String> values) {
            addCriterion("CreatedName in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotIn(List<String> values) {
            addCriterion("CreatedName not in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameBetween(String value1, String value2) {
            addCriterion("CreatedName between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotBetween(String value1, String value2) {
            addCriterion("CreatedName not between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDIsNull() {
            addCriterion("IsOpenContractSignSetGUID is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDIsNotNull() {
            addCriterion("IsOpenContractSignSetGUID is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDEqualTo(String value) {
            addCriterion("IsOpenContractSignSetGUID =", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDNotEqualTo(String value) {
            addCriterion("IsOpenContractSignSetGUID <>", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDGreaterThan(String value) {
            addCriterion("IsOpenContractSignSetGUID >", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("IsOpenContractSignSetGUID >=", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDLessThan(String value) {
            addCriterion("IsOpenContractSignSetGUID <", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDLessThanOrEqualTo(String value) {
            addCriterion("IsOpenContractSignSetGUID <=", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDLike(String value) {
            addCriterion("IsOpenContractSignSetGUID like", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDNotLike(String value) {
            addCriterion("IsOpenContractSignSetGUID not like", value, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDIn(List<String> values) {
            addCriterion("IsOpenContractSignSetGUID in", values, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDNotIn(List<String> values) {
            addCriterion("IsOpenContractSignSetGUID not in", values, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDBetween(String value1, String value2) {
            addCriterion("IsOpenContractSignSetGUID between", value1, value2, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andIsOpenContractSignSetGUIDNotBetween(String value1, String value2) {
            addCriterion("IsOpenContractSignSetGUID not between", value1, value2, "isOpenContractSignSetGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNull() {
            addCriterion("ModifiedGUID is null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIsNotNull() {
            addCriterion("ModifiedGUID is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDEqualTo(String value) {
            addCriterion("ModifiedGUID =", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotEqualTo(String value) {
            addCriterion("ModifiedGUID <>", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThan(String value) {
            addCriterion("ModifiedGUID >", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID >=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThan(String value) {
            addCriterion("ModifiedGUID <", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLessThanOrEqualTo(String value) {
            addCriterion("ModifiedGUID <=", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDLike(String value) {
            addCriterion("ModifiedGUID like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotLike(String value) {
            addCriterion("ModifiedGUID not like", value, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDIn(List<String> values) {
            addCriterion("ModifiedGUID in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotIn(List<String> values) {
            addCriterion("ModifiedGUID not in", values, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDBetween(String value1, String value2) {
            addCriterion("ModifiedGUID between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedGUIDNotBetween(String value1, String value2) {
            addCriterion("ModifiedGUID not between", value1, value2, "modifiedGUID");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNull() {
            addCriterion("ModifiedName is null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIsNotNull() {
            addCriterion("ModifiedName is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedNameEqualTo(String value) {
            addCriterion("ModifiedName =", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotEqualTo(String value) {
            addCriterion("ModifiedName <>", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThan(String value) {
            addCriterion("ModifiedName >", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedName >=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThan(String value) {
            addCriterion("ModifiedName <", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLessThanOrEqualTo(String value) {
            addCriterion("ModifiedName <=", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameLike(String value) {
            addCriterion("ModifiedName like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotLike(String value) {
            addCriterion("ModifiedName not like", value, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameIn(List<String> values) {
            addCriterion("ModifiedName in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotIn(List<String> values) {
            addCriterion("ModifiedName not in", values, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameBetween(String value1, String value2) {
            addCriterion("ModifiedName between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedNameNotBetween(String value1, String value2) {
            addCriterion("ModifiedName not between", value1, value2, "modifiedName");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("ModifiedTime is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("ModifiedTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("ModifiedTime =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("ModifiedTime <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("ModifiedTime >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("ModifiedTime <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("ModifiedTime <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("ModifiedTime in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("ModifiedTime not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("ModifiedTime not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNull() {
            addCriterion("VersionNumber is null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNotNull() {
            addCriterion("VersionNumber is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberEqualTo(Long value) {
            addCriterion("VersionNumber =", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotEqualTo(Long value) {
            addCriterion("VersionNumber <>", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThan(Long value) {
            addCriterion("VersionNumber >", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("VersionNumber >=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThan(Long value) {
            addCriterion("VersionNumber <", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThanOrEqualTo(Long value) {
            addCriterion("VersionNumber <=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIn(List<Long> values) {
            addCriterion("VersionNumber in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotIn(List<Long> values) {
            addCriterion("VersionNumber not in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberBetween(Long value1, Long value2) {
            addCriterion("VersionNumber between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotBetween(Long value1, Long value2) {
            addCriterion("VersionNumber not between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIsNull() {
            addCriterion("is_testdata is null");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIsNotNull() {
            addCriterion("is_testdata is not null");
            return (Criteria) this;
        }

        public Criteria andIs_testdataEqualTo(Integer value) {
            addCriterion("is_testdata =", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotEqualTo(Integer value) {
            addCriterion("is_testdata <>", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataGreaterThan(Integer value) {
            addCriterion("is_testdata >", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_testdata >=", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataLessThan(Integer value) {
            addCriterion("is_testdata <", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataLessThanOrEqualTo(Integer value) {
            addCriterion("is_testdata <=", value, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataIn(List<Integer> values) {
            addCriterion("is_testdata in", values, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotIn(List<Integer> values) {
            addCriterion("is_testdata not in", values, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataBetween(Integer value1, Integer value2) {
            addCriterion("is_testdata between", value1, value2, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_testdataNotBetween(Integer value1, Integer value2) {
            addCriterion("is_testdata not between", value1, value2, "is_testdata");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIs_deletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "is_deleted");
            return (Criteria) this;
        }

        public Criteria andIs_deletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "is_deleted");
            return (Criteria) this;
        }
    }

    /**
     * x_s_isopencontractsignset
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * x_s_isopencontractsignset null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}