package com.example.demo.entity.generatePackage;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Created by Mybatis Generator on 2021/05/21
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IsOpenContractSignSetEntity implements Serializable {
    /**
     */
    private Long id;

    /**
     */
    private String xBUGUID;

    /**
     */
    private Date xCloseDate;

    /**
     */
    private String xCloseReason;

    /**
     */
    private Integer xCloseReasonEnum;

    /**
     */
    private String xIsOpenSign;

    /**
     */
    private Integer xIsOpenSignEnum;

    /**
     */
    private Date xOpenDate;

    /**
     */
    private String xProjGUID;

    /**
     */
    private Date xRYCloseDate;

    /**
     */
    private String createdGUID;

    /**
     */
    private String createdName;

    /**
     */
    private Date createdTime;

    /**
     */
    private String isOpenContractSignSetGUID;

    /**
     */
    private String modifiedGUID;

    /**
     */
    private String modifiedName;

    /**
     */
    private Date modifiedTime;

    /**
     */
    private Long versionNumber;

    /**
     */
    private Integer is_testdata;

    /**
     */
    private Integer is_deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_s_isopencontractsignset
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xBUGUID=").append(xBUGUID);
        sb.append(", xCloseDate=").append(xCloseDate);
        sb.append(", xCloseReason=").append(xCloseReason);
        sb.append(", xCloseReasonEnum=").append(xCloseReasonEnum);
        sb.append(", xIsOpenSign=").append(xIsOpenSign);
        sb.append(", xIsOpenSignEnum=").append(xIsOpenSignEnum);
        sb.append(", xOpenDate=").append(xOpenDate);
        sb.append(", xProjGUID=").append(xProjGUID);
        sb.append(", xRYCloseDate=").append(xRYCloseDate);
        sb.append(", createdGUID=").append(createdGUID);
        sb.append(", createdName=").append(createdName);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", isOpenContractSignSetGUID=").append(isOpenContractSignSetGUID);
        sb.append(", modifiedGUID=").append(modifiedGUID);
        sb.append(", modifiedName=").append(modifiedName);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", versionNumber=").append(versionNumber);
        sb.append(", is_testdata=").append(is_testdata);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}