package com.example.demo.entity.generatePackage;

import java.io.Serializable;
import java.util.Date;

public class SSaleServiceDto implements Serializable {
    /**
     * 
    * s_SaleServiceGUID
     */
    private String sSaleserviceguid;

    /**
     * 
    * CreatedTime
     */
    private Date createdtime;

    /**
     * 
    * CreatedGUID
     */
    private String createdguid;

    /**
     * 
    * CreatedName
     */
    private String createdname;

    /**
     * 
    * ModifiedTime
     */
    private Date modifiedtime;

    /**
     * 
    * ModifiedGUID
     */
    private String modifiedguid;

    /**
     * 
    * ModifiedName
     */
    private String modifiedname;

    /**
     * 
    * VersionNumber
     */
    private Date versionnumber;

    /**
     * 
    * ServiceProc
     */
    private String serviceproc;

    /**
     * 
    * BgnDate
     */
    private Date bgndate;

    /**
     * 
    * EndDate
     */
    private Date enddate;

    /**
     * 
    * CompleteDate
     */
    private Date completedate;

    /**
     * 
    * NotRcvFiles
     */
    private String notrcvfiles;

    /**
     * 
    * IsFull
     */
    private Integer isfull;

    /**
     * 
    * Sort
     */
    private Integer sort;

    /**
     * 
    * YblAjApplyTime
     */
    private Date yblajapplytime;

    /**
     * 
    * YfkTime
     */
    private Date yfktime;

    /**
     * 
    * IsJump
     */
    private Integer isjump;

    /**
     * 
    * ProjGUID
     */
    private String projguid;

    /**
     * 
    * ServiceItem
     */
    private String serviceitem;

    /**
     * 
    * ServiceProcCode
     */
    private Integer serviceproccode;

    /**
     * 
    * ServiceItemEnum
     */
    private Integer serviceitemenum;

    /**
     * 
    * SaleGUID
     */
    private String saleguid;

    /**
     * 
    * ExpiryDays
     */
    private Integer expirydays;

    /**
     * 
    * x_cqbdcfph
     */
    private String xCqbdcfph;

    /**
     * 
    * x_cqblfs
     */
    private String xCqblfs;

    /**
     * 
    * x_cqfflx
     */
    private String xCqfflx;

    /**
     * 
    * x_cqjzh
     */
    private String xCqjzh;

    /**
     * 
    * x_cqlqr
     */
    private String xCqlqr;

    /**
     * 
    * x_cqqzh
     */
    private String xCqqzh;

    /**
     * 
    * x_cqstbh
     */
    private String xCqstbh;

    /**
     * 
    * x_cqzjrq
     */
    private Date xCqzjrq;

    /**
     * 
    * x_Gsfsl
     */
    private Date xGsfsl;

    /**
     * 
    * x_Khgz
     */
    private String xKhgz;

    /**
     * 
    * x_Yhbl
     */
    private String xYhbl;

    /**
     * 
    * x_Yhfht
     */
    private Date xYhfht;

    /**
     * 
    * x_YjXdDate
     */
    private Date xYjxddate;

    /**
     * 
    * x_HandoverDate
     */
    private Date xHandoverdate;

    /**
     * 
    * x_HandoverOperator
     */
    private String xHandoveroperator;

    /**
     * 
    * x_HandoverStatus
     */
    private String xHandoverstatus;

    /**
     * 
    * x_HandoverStatus1
     */
    private String xHandoverstatus1;

    /**
     * 
    * x_HandoverStatusEnum1
     */
    private Integer xHandoverstatusenum1;

    /**
     * 
    * x_yhfdkhtsj
     */
    private Date xYhfdkhtsj;

    /**
     * 
    * x_IsGovernmentSign
     */
    private String xIsgovernmentsign;

    /**
     * 
    * x_NetSignDate
     */
    private Date xNetsigndate;

    /**
     * 
    * ServiceMemo
     */
    private String servicememo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_saleservice_order_mock
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getsSaleserviceguid() {
        return sSaleserviceguid;
    }

    public void setsSaleserviceguid(String sSaleserviceguid) {
        this.sSaleserviceguid = sSaleserviceguid == null ? null : sSaleserviceguid.trim();
    }

    public Date getCreatedtime() {
        return createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    public String getCreatedguid() {
        return createdguid;
    }

    public void setCreatedguid(String createdguid) {
        this.createdguid = createdguid == null ? null : createdguid.trim();
    }

    public String getCreatedname() {
        return createdname;
    }

    public void setCreatedname(String createdname) {
        this.createdname = createdname == null ? null : createdname.trim();
    }

    public Date getModifiedtime() {
        return modifiedtime;
    }

    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    public String getModifiedguid() {
        return modifiedguid;
    }

    public void setModifiedguid(String modifiedguid) {
        this.modifiedguid = modifiedguid == null ? null : modifiedguid.trim();
    }

    public String getModifiedname() {
        return modifiedname;
    }

    public void setModifiedname(String modifiedname) {
        this.modifiedname = modifiedname == null ? null : modifiedname.trim();
    }

    public Date getVersionnumber() {
        return versionnumber;
    }

    public void setVersionnumber(Date versionnumber) {
        this.versionnumber = versionnumber;
    }

    public String getServiceproc() {
        return serviceproc;
    }

    public void setServiceproc(String serviceproc) {
        this.serviceproc = serviceproc == null ? null : serviceproc.trim();
    }

    public Date getBgndate() {
        return bgndate;
    }

    public void setBgndate(Date bgndate) {
        this.bgndate = bgndate;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public Date getCompletedate() {
        return completedate;
    }

    public void setCompletedate(Date completedate) {
        this.completedate = completedate;
    }

    public String getNotrcvfiles() {
        return notrcvfiles;
    }

    public void setNotrcvfiles(String notrcvfiles) {
        this.notrcvfiles = notrcvfiles == null ? null : notrcvfiles.trim();
    }

    public Integer getIsfull() {
        return isfull;
    }

    public void setIsfull(Integer isfull) {
        this.isfull = isfull;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getYblajapplytime() {
        return yblajapplytime;
    }

    public void setYblajapplytime(Date yblajapplytime) {
        this.yblajapplytime = yblajapplytime;
    }

    public Date getYfktime() {
        return yfktime;
    }

    public void setYfktime(Date yfktime) {
        this.yfktime = yfktime;
    }

    public Integer getIsjump() {
        return isjump;
    }

    public void setIsjump(Integer isjump) {
        this.isjump = isjump;
    }

    public String getProjguid() {
        return projguid;
    }

    public void setProjguid(String projguid) {
        this.projguid = projguid == null ? null : projguid.trim();
    }

    public String getServiceitem() {
        return serviceitem;
    }

    public void setServiceitem(String serviceitem) {
        this.serviceitem = serviceitem == null ? null : serviceitem.trim();
    }

    public Integer getServiceproccode() {
        return serviceproccode;
    }

    public void setServiceproccode(Integer serviceproccode) {
        this.serviceproccode = serviceproccode;
    }

    public Integer getServiceitemenum() {
        return serviceitemenum;
    }

    public void setServiceitemenum(Integer serviceitemenum) {
        this.serviceitemenum = serviceitemenum;
    }

    public String getSaleguid() {
        return saleguid;
    }

    public void setSaleguid(String saleguid) {
        this.saleguid = saleguid == null ? null : saleguid.trim();
    }

    public Integer getExpirydays() {
        return expirydays;
    }

    public void setExpirydays(Integer expirydays) {
        this.expirydays = expirydays;
    }

    public String getxCqbdcfph() {
        return xCqbdcfph;
    }

    public void setxCqbdcfph(String xCqbdcfph) {
        this.xCqbdcfph = xCqbdcfph == null ? null : xCqbdcfph.trim();
    }

    public String getxCqblfs() {
        return xCqblfs;
    }

    public void setxCqblfs(String xCqblfs) {
        this.xCqblfs = xCqblfs == null ? null : xCqblfs.trim();
    }

    public String getxCqfflx() {
        return xCqfflx;
    }

    public void setxCqfflx(String xCqfflx) {
        this.xCqfflx = xCqfflx == null ? null : xCqfflx.trim();
    }

    public String getxCqjzh() {
        return xCqjzh;
    }

    public void setxCqjzh(String xCqjzh) {
        this.xCqjzh = xCqjzh == null ? null : xCqjzh.trim();
    }

    public String getxCqlqr() {
        return xCqlqr;
    }

    public void setxCqlqr(String xCqlqr) {
        this.xCqlqr = xCqlqr == null ? null : xCqlqr.trim();
    }

    public String getxCqqzh() {
        return xCqqzh;
    }

    public void setxCqqzh(String xCqqzh) {
        this.xCqqzh = xCqqzh == null ? null : xCqqzh.trim();
    }

    public String getxCqstbh() {
        return xCqstbh;
    }

    public void setxCqstbh(String xCqstbh) {
        this.xCqstbh = xCqstbh == null ? null : xCqstbh.trim();
    }

    public Date getxCqzjrq() {
        return xCqzjrq;
    }

    public void setxCqzjrq(Date xCqzjrq) {
        this.xCqzjrq = xCqzjrq;
    }

    public Date getxGsfsl() {
        return xGsfsl;
    }

    public void setxGsfsl(Date xGsfsl) {
        this.xGsfsl = xGsfsl;
    }

    public String getxKhgz() {
        return xKhgz;
    }

    public void setxKhgz(String xKhgz) {
        this.xKhgz = xKhgz == null ? null : xKhgz.trim();
    }

    public String getxYhbl() {
        return xYhbl;
    }

    public void setxYhbl(String xYhbl) {
        this.xYhbl = xYhbl == null ? null : xYhbl.trim();
    }

    public Date getxYhfht() {
        return xYhfht;
    }

    public void setxYhfht(Date xYhfht) {
        this.xYhfht = xYhfht;
    }

    public Date getxYjxddate() {
        return xYjxddate;
    }

    public void setxYjxddate(Date xYjxddate) {
        this.xYjxddate = xYjxddate;
    }

    public Date getxHandoverdate() {
        return xHandoverdate;
    }

    public void setxHandoverdate(Date xHandoverdate) {
        this.xHandoverdate = xHandoverdate;
    }

    public String getxHandoveroperator() {
        return xHandoveroperator;
    }

    public void setxHandoveroperator(String xHandoveroperator) {
        this.xHandoveroperator = xHandoveroperator == null ? null : xHandoveroperator.trim();
    }

    public String getxHandoverstatus() {
        return xHandoverstatus;
    }

    public void setxHandoverstatus(String xHandoverstatus) {
        this.xHandoverstatus = xHandoverstatus == null ? null : xHandoverstatus.trim();
    }

    public String getxHandoverstatus1() {
        return xHandoverstatus1;
    }

    public void setxHandoverstatus1(String xHandoverstatus1) {
        this.xHandoverstatus1 = xHandoverstatus1 == null ? null : xHandoverstatus1.trim();
    }

    public Integer getxHandoverstatusenum1() {
        return xHandoverstatusenum1;
    }

    public void setxHandoverstatusenum1(Integer xHandoverstatusenum1) {
        this.xHandoverstatusenum1 = xHandoverstatusenum1;
    }

    public Date getxYhfdkhtsj() {
        return xYhfdkhtsj;
    }

    public void setxYhfdkhtsj(Date xYhfdkhtsj) {
        this.xYhfdkhtsj = xYhfdkhtsj;
    }

    public String getxIsgovernmentsign() {
        return xIsgovernmentsign;
    }

    public void setxIsgovernmentsign(String xIsgovernmentsign) {
        this.xIsgovernmentsign = xIsgovernmentsign == null ? null : xIsgovernmentsign.trim();
    }

    public Date getxNetsigndate() {
        return xNetsigndate;
    }

    public void setxNetsigndate(Date xNetsigndate) {
        this.xNetsigndate = xNetsigndate;
    }

    public String getServicememo() {
        return servicememo;
    }

    public void setServicememo(String servicememo) {
        this.servicememo = servicememo == null ? null : servicememo.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sSaleserviceguid=").append(sSaleserviceguid);
        sb.append(", createdtime=").append(createdtime);
        sb.append(", createdguid=").append(createdguid);
        sb.append(", createdname=").append(createdname);
        sb.append(", modifiedtime=").append(modifiedtime);
        sb.append(", modifiedguid=").append(modifiedguid);
        sb.append(", modifiedname=").append(modifiedname);
        sb.append(", versionnumber=").append(versionnumber);
        sb.append(", serviceproc=").append(serviceproc);
        sb.append(", bgndate=").append(bgndate);
        sb.append(", enddate=").append(enddate);
        sb.append(", completedate=").append(completedate);
        sb.append(", notrcvfiles=").append(notrcvfiles);
        sb.append(", isfull=").append(isfull);
        sb.append(", sort=").append(sort);
        sb.append(", yblajapplytime=").append(yblajapplytime);
        sb.append(", yfktime=").append(yfktime);
        sb.append(", isjump=").append(isjump);
        sb.append(", projguid=").append(projguid);
        sb.append(", serviceitem=").append(serviceitem);
        sb.append(", serviceproccode=").append(serviceproccode);
        sb.append(", serviceitemenum=").append(serviceitemenum);
        sb.append(", saleguid=").append(saleguid);
        sb.append(", expirydays=").append(expirydays);
        sb.append(", xCqbdcfph=").append(xCqbdcfph);
        sb.append(", xCqblfs=").append(xCqblfs);
        sb.append(", xCqfflx=").append(xCqfflx);
        sb.append(", xCqjzh=").append(xCqjzh);
        sb.append(", xCqlqr=").append(xCqlqr);
        sb.append(", xCqqzh=").append(xCqqzh);
        sb.append(", xCqstbh=").append(xCqstbh);
        sb.append(", xCqzjrq=").append(xCqzjrq);
        sb.append(", xGsfsl=").append(xGsfsl);
        sb.append(", xKhgz=").append(xKhgz);
        sb.append(", xYhbl=").append(xYhbl);
        sb.append(", xYhfht=").append(xYhfht);
        sb.append(", xYjxddate=").append(xYjxddate);
        sb.append(", xHandoverdate=").append(xHandoverdate);
        sb.append(", xHandoveroperator=").append(xHandoveroperator);
        sb.append(", xHandoverstatus=").append(xHandoverstatus);
        sb.append(", xHandoverstatus1=").append(xHandoverstatus1);
        sb.append(", xHandoverstatusenum1=").append(xHandoverstatusenum1);
        sb.append(", xYhfdkhtsj=").append(xYhfdkhtsj);
        sb.append(", xIsgovernmentsign=").append(xIsgovernmentsign);
        sb.append(", xNetsigndate=").append(xNetsigndate);
        sb.append(", servicememo=").append(servicememo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}